apiVersion: v1
kind: Service
metadata:
  name: calibre-web
  labels:
    app: calibre-web
spec:
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: calibre-web
  selector:
    app: calibre-web