global:
  debug: true
cluster-issuer:
  self-signed: true
nextcloud:
  host: nextcloud.localhost
  cluster-issuer: self-signed
pgadmin:
  host: pgadmin.localhost
  cluster-issuer: self-signed
calibre-web:
  host: calibre.localhost
  cluster-issuer: self-signed
