cluster-issuer:
    email: ENC[AES256_GCM,data:GYQ8vHdoIZS/S+EGbZ+8AOYuGpWFrMI=,iv:grY4VNdvGE1r5Ssq0iCVoKNgq2hetaqMax1Zb6p98mA=,tag:rPCXm4jGPkc++252BfVPTg==,type:str]
nextcloud:
    host: ENC[AES256_GCM,data:mgoiA+dH3u103jAc7swXdA==,iv:VfqgNzAgjrrZJkcpz/1tlqNtiULq6TCZfl0TRkvA8KE=,tag:hjg5J+GqZxLcJkDJt//Z/Q==,type:str]
pgadmin:
    host: ENC[AES256_GCM,data:0ZdcYOYmtGtzG6MbRXqCSFSlb8+Hd6ZRSw==,iv:JAcULPKg0MMC150H52tjDrc8MOgqAcmY1L4JMgsksWE=,tag:ZE4/j3iaEjqBfN5iVbcHRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://k8s-web-kv.vault.azure.net
          name: sops-key
          version: 6fa73ecbe2c44d0b85a269f9f9660035
          created_at: "2022-12-25T06:36:34Z"
          enc: BY_kROV-yMPbCBNB30aDyT7ARYh-rD6TCje1Z93xgRpXTqR8IWJuepMN7bLod21EVuFJduZOgm9-i_zLE1fFkT2kVq6hvU6wXN3qKNM7c1siyN69x9G-6w53C97rflI_s-OyXlHnyfyMqLGhW7RgK5Pd2HPLjuEoTV_EKA5D0a8H5Yq9-EG7vBLUibmMTvfobPyGqgyDrwIdRnYxUAH639HgXSimI5n7kY2_ZqPAKzp1IzXkeGP5kMKrNntbVObx0cHNCDrp3t_YnW5D9guoaW7Nx1BWYwknX7rngHEn-e9EsKOpGrGMP547vfiPrP1q7UXPNrQYlN5VoCpI6nIgjg
    hc_vault: []
    age: []
    lastmodified: "2022-12-25T06:37:42Z"
    mac: ENC[AES256_GCM,data:KFjJkKQccr8tRcvIeiW3IvouqXyvr+a4pqgRYIW1Sqm1hh8B3YX3KMfVtCAQSbW+aOPmnmlxfEHilhFO0nep/07Ly5drg0iuxU3F9y9uye0LrTQ1yfEyJW/DFKVSZ70KGIGXyeUHUCUqDiNbIqvekXoAfrx75Ci/PMx1/+04YQg=,iv:H/DHyouUT4aOENdpWHML+8KFoChuw8dIip+FV2sPE2M=,tag:Lab4oaMETLlXwk0fRKaNAg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
