cluster-issuer:
    email: ENC[AES256_GCM,data:GYQ8vHdoIZS/S+EGbZ+8AOYuGpWFrMI=,iv:grY4VNdvGE1r5Ssq0iCVoKNgq2hetaqMax1Zb6p98mA=,tag:rPCXm4jGPkc++252BfVPTg==,type:str]
nextcloud:
    host: ENC[AES256_GCM,data:mgoiA+dH3u103jAc7swXdA==,iv:VfqgNzAgjrrZJkcpz/1tlqNtiULq6TCZfl0TRkvA8KE=,tag:hjg5J+GqZxLcJkDJt//Z/Q==,type:str]
pgadmin:
    host: ENC[AES256_GCM,data:0ZdcYOYmtGtzG6MbRXqCSFSlb8+Hd6ZRSw==,iv:JAcULPKg0MMC150H52tjDrc8MOgqAcmY1L4JMgsksWE=,tag:ZE4/j3iaEjqBfN5iVbcHRQ==,type:str]
calibre-web:
    host: ENC[AES256_GCM,data:W0/mGtxzySC2Rb811qqnug==,iv:EtJhnl2FeRpzxUuvd/iSoURFk1qpmQYsXlsn7Du+Ajo=,tag:4aog7Tjq943yKLb3IeSCEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://k8s-web-kv.vault.azure.net
          name: sops-key
          version: 6fa73ecbe2c44d0b85a269f9f9660035
          created_at: "2022-12-25T06:36:34Z"
          enc: BY_kROV-yMPbCBNB30aDyT7ARYh-rD6TCje1Z93xgRpXTqR8IWJuepMN7bLod21EVuFJduZOgm9-i_zLE1fFkT2kVq6hvU6wXN3qKNM7c1siyN69x9G-6w53C97rflI_s-OyXlHnyfyMqLGhW7RgK5Pd2HPLjuEoTV_EKA5D0a8H5Yq9-EG7vBLUibmMTvfobPyGqgyDrwIdRnYxUAH639HgXSimI5n7kY2_ZqPAKzp1IzXkeGP5kMKrNntbVObx0cHNCDrp3t_YnW5D9guoaW7Nx1BWYwknX7rngHEn-e9EsKOpGrGMP547vfiPrP1q7UXPNrQYlN5VoCpI6nIgjg
    hc_vault: []
    age: []
    lastmodified: "2023-01-14T08:33:22Z"
    mac: ENC[AES256_GCM,data:93DPjnKoLFrgOiS9hd752KkIVT7eHgLFums4wCBiZTC83sebZDokG1r4FwhzjpQmay7toICF1jk378H/jfDutg8yxQJwT3mh3d1WiE8CU3/QIGv0YmFAqAjgHlbQt2/VSkFR8zG7SYF4la/gSE9KS3QZg+/roMT8pZ6FDvMhXZA=,iv:qMltbzVi5VIEIbQI4cw1oZoNoleNkicap9QbBdCWQUw=,tag:3sdFi5KYpBf2clzS6IsaEQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
