{{- if not .Values.debug }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pgadmin-storage-class
provisioner: blob.csi.azure.com
parameters:
  protocol: fuse
  resourceGroup: {{ index .Values.pgadmin "resource-group" }}
  storageAccount: {{ index .Values.pgadmin "storage-account" }}
  storeAccountKey: "false"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=10
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
  - --log-level=LOG_WARNING
  - --cache-size-mb=1024
{{- end }}
