apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-user-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "nextcloud"
type: Opaque
data:
  username: {{ .Values.nextcloud.username | b64enc | quote }}
  password: {{ .Values.nextcloud.password | b64enc | quote }}
  smtp-username: ""
  smtp-password: ""
