apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-user-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "pgadmin"
type: Opaque
data:
  password: {{ .Values.pgadmin.password | b64enc | quote }}
