apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-image-pull-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "nextcloud"
type: kubernetes.io/dockercfg
stringData:
  .dockercfg: |
    {
      "auths": {
        "ghcr.io": {
          "username": "{{ .Values.github.username }}",
          "password": "{{ .Values.github.password }}"
        }
      }
    }
