{{- if not .Values.debug }}
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-storage-secret
type: Opaque
data:
  azurestorageaccountname: {{ index .Values.nextcloud.data "storage-account" | b64enc | quote }}
  azurestorageaccountkey: {{ index .Values.nextcloud.data "storage-account-key" | b64enc | quote }}
{{- end }}
