{{- if not .Values.debug }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  capacity:
    storage: {{ .Values.nextcloud.data.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: nextcloud-share
    volumeAttributes:
      resourceGroup: {{ index .Values.nextcloud.data "resource-group" }}
      shareName: {{ index .Values.nextcloud.data "share-name" }}
    nodeStageSecretRef:
      name: nextcloud-storage-secret
      namespace: nextcloud
  mountOptions:
    - dir_mode=0770
    - file_mode=0770
    - uid=33
    - gid=33
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
{{- end }}
