name: Deploy helmfile to Kubernetes cluster

on:
  push:
    branches:
    - main
    paths:
    - '*/**'
    - '!dockers/**'
    - '!.github/**'
    - .github/workflows/helmfile.yaml
    - '*.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.2.0

    - name: Test
      run: |
        helmfile --version
        helm version
        kubectl version --client