name: Deploy helmfile to Kubernetes cluster

on:
  push:
    branches:
    - main
    paths:
    - '*/**'
    - '!.github/**'
    - '!dockers/**'
    - '.github/workflows/helmfile.yaml'
    - '*.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure login
      id: login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: '${{ secrets.resource_group }}' 
        cluster-name: '${{ secrets.cluster_name }}'

    - name: Setup kubectl
      id: install-kubectl
      uses: azure/setup-kubectl@v3

    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.2.0
      with:
        install-kubectl: false
        additional-helm-plugins: https://github.com/jkroepke/helm-secrets --version v4.1.1

    - name: Sops Binary Installer
      uses: mdgreenwald/mozilla-sops-action@v1.4.1

    - name: Deploy helmfile
      run: helmfile apply helmfile.yaml -e prod

