controller:
    service:
        annotations:
            service.beta.kubernetes.io/azure-load-balancer-resource-group: ENC[AES256_GCM,data:X3fz0LVPS3o=,iv:idSxabeQfIaZCf8OmQjh8Dpf7/2104n03q9ytyOvoXQ=,tag:mozsSdmvBLzMCtoI5dnt4g==,type:str]
        loadBalancerIP: ENC[AES256_GCM,data:3bp7Tj3pNSS9I0gb2w==,iv:NfRFHND7+GtOtpxLjwhQ5GJcHQR7dW0EuVAaW0V8JFM=,tag:oxMA2WuBW6UEBE+9Yp+H/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://k8s-web-kv.vault.azure.net
          name: sops-key
          version: 6fa73ecbe2c44d0b85a269f9f9660035
          created_at: "2022-12-25T05:46:07Z"
          enc: UbVovGtPepzbVeI266VkkPePCmSoQ3ufdjmykaI_g3AVXQZWwA2t7KBTTPxl0AMPLPMMB00Fvcxke67KTxchtKJ_j464KrRU_cE7fcT94fafih7_1K41ML4gImkjDKm0WNKCUQZkseQTCjbO4goDYHcoWkuFq-aNWxQuH_MaMGNuMa-9Eyy27IG_QnXEnjRXg54haHqBXjxpotjufQTVvt0YMjcCArPSzz9V9sX4g81zYzJePErL4aezdqfuxPHTAnz9GQMQ2Z0gm21orOpf3NtyQkAo3asqbNTu0GNW3LzSk5cc509or3-SQEnZmP0wJtBkiBlyME1o5jJyjryMLw
    hc_vault: []
    age: []
    lastmodified: "2022-12-25T06:26:42Z"
    mac: ENC[AES256_GCM,data:/vXOqHcd78Xya61DwrIbwgF6GZ22T0aKVfd6/VEwXxj4vwNcwO7DsLUq6NSXEHmR1mHgLBHp+X/DhRxxZEg7K3SbtgOibxxEV1W/aS94Ozvu9HA6jA/iFyyE699jyD5dSMoqH8H5aCjhrcB4UcHKZ/aNDblvHubhc5/o6KlPQk0=,iv:SgU0UeUPCZqjozGPhm09ygBRlLTrHdIHqqbWi0nJnKo=,tag:A9XHo0tqbTInO1VKCV6Gcw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
